/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class FindRequest extends SpeakeasyBase {
  /**
   * The name of the company the person works for
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=company",
  })
  company?: string;

  /**
   * The domain of the company the person works for
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=company_domain",
  })
  companyDomain?: string;

  /**
   * The email address to look up
   */
  @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=email" })
  email: string;

  /**
   * The person's Facebook profile URL
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=facebook",
  })
  facebook?: string;

  /**
   * The person's last name. If you have this, passing this is strongly recommended to improve match rates
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=family_name",
  })
  familyName?: string;

  /**
   * The person's first name
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=given_name",
  })
  givenName?: string;

  /**
   * The person's IP address. If you have this, passing this is strongly recommended to improve match rates
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=ip_address",
  })
  ipAddress?: string;

  /**
   * The person's LinkedIn profile URL
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=linkedin",
  })
  linkedin?: string;

  /**
   * The city or country where the person lives
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=location",
  })
  location?: string;

  /**
   * The person's Twitter profile username
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=twitter",
  })
  twitter?: string;

  /**
   * A webhook URL that results will be sent to
   */
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=webhook_url",
  })
  webhookUrl?: string;
}

export class FindResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  /**
   * Successful lookup, person encoded in the response body
   */
  @SpeakeasyMetadata()
  person?: shared.Person;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;
}
